config/routes.rb
Img::Application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root :to => 'home#index'
  resources :images, :only => [:show, :create, :destroy]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :session, :class_name => "ActiveRecord::SessionStore::Session"

  has_attached_file :image, :styles => { :medium => "800x", :thumb => "200x" }, :url => "/images/:hash.:extension", :hash_secret => "0xDECAFBAD"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  after_create :generate_token

  default_scope { order('id DESC') }

  def to_param
    token
  end
  
  def to_s
    "Image ##{id}"
  end

  private

  def generate_token
    self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
    self.save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_session
    @current_session ||= ActiveRecord::SessionStore::Session.where(:session_id => request.session_options[:id]).first
    @current_session
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    unless current_session.nil?
      @images = Image.where(:session_id => current_session.id).order(:id => :desc)
    else
      @images = []
    end
    @image = Image.new
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def create
    @image = Image.new(image_params)
    @image.remote_addr = request.remote_ip
    @image.session = current_session
    @image.save
    respond_to do |f|
      f.html do
        flash[:notice] = 'The image has been created successfully'
        redirect_to image_path(@image.token)
      end
      
      f.json do
        render :json => {
          :thumbnail => @image.image.url(:thumb),
          :link => image_path(@image.token)
        }
      end
    end
  end

  def show
    @image = Image.where(:token => params[:id]).first
  end

  def destroy
    @image = Image.where(:token => params[:id]).first
    @image.destroy
    flash[:notice] = 'The image has been deleted successfully'
    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_class(path)
    "active" if current_page?(path)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper

  def absolute_attachment_url(attachment_name, attachment_style = :original)
    "#{request.protocol}#{request.host_with_port}#{attachment_name.url(attachment_style)}"
  end

end

app/views/home/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Upload
  </div>
  <div class="panel-body">
    <p>Please select your image and press upload.</p>
    <%= form_for @image, :html => { :multipart => true } do |f| %>
      <p>
        <%= f.file_field :image, :multiple => true, :name => "image[image]" %>
      </p>
    <% end %>
  </div>
</div>

<h2>My Uploads</h2>

<table id="uploads_table" class="table table-striped">
  <thead>
    <tr>
      <th>Thumbnail</th>
      <th>Filename</th>
      <th>Progress</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    <% if @images.any? %>
      <% @images.each do |image| %>
        <tr>
          <td><%= image_tag image.image.url(:thumb) %></td>
          <td><%= image.image_file_name %></td>
          <td class="upload">
            <div class="progress"><div class="bar" style="width: 100%;"></div></div>
          </td>
          <td><%= link_to 'show', image %></td>
        </tr>    
      <% end %>
    <% else %>
      <tr id="placeholder">
        <td colspan="4">
          no uploads yet
        </td>
      </tr>
    <% end %>
  </tobody>
</table>

<script id="template-upload" type="text/x-tmpl">
  <tr>
    <td class="preview">-</td>
    <td>{%= o.name %}</td>
    <td class="upload">
      <div class="progress"><div class="bar" style="width: 0%;"></div></div>
    </td>
    <td class="link">-</td>
  </tr>
</script>

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<p>Find me in app/views/images/edit.html.erb</p>

app/views/images/show.html.erb
<%= link_to @image.image.url, :class => 'thumbnail' do %>
  <%= image_tag @image.image.url :medium %>
<% end %>

<table class="table">
  <tr>
    <th>Uploaded</th>
    <td><%= l @image.created_at %>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= image_url(@image.token) %></td>
  </tr>
  <tr>
    <th>Directlink</th>
    <td><%= absolute_attachment_url(@image.image) %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IMG</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, :class => 'navbar-brand' do %>
            <span class="glyphicon glyphicon-link"></span>
            IMG
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <%= content_tag :li, :class => active_class(root_path) do %>
              <%= link_to root_path do %>
                <span class="glyphicon glyphicon-home"></span>
                Home
              <% end %>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if admin_user_signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="glyphicon glyphicon-user"></span>
                      <%= current_admin_user.email %>
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to admin_root_path do %>
                          <span class="glyphicon glyphicon-wrench"></span>
                          Admin
                        <% end %>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to destroy_admin_user_session_path do %>
                          <span class="glyphicon glyphicon-log-out"></span>
                          Logout
                        <% end %>
                      </li>
                    </ul>
                  </li>
                </ul>
              <% else %>
                <%= link_to admin_root_path do %>
                  <span class="glyphicon glyphicon-log-in"></span>
                  Login
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>